title: "Mizanur Rahman"
## author: "Mizanur Rahman"
## description: "Data Science \n Statistics \n Finance"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: true       # show a sidebar instead of the usual header

# Menu

navigation:
  - {title: "About Me", url: "/", icon: github} # icon: user
  - {title: "Blog", file: "blog.md"}  # icon: food 
  - {title: "Resume", url: "/mizanur_cv.pdf"} # icon: file 


external:                  # see http://fontawesome.com/icons
  - {title: Email, icon: envelope, url: "mailto:mizanur55@hotmail.com"}
  - {title: Github, icon: github, url: "https://github.com/mizanur55"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/mizanur-rahman-58a86b106/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
